# Provides a configuration for running Butler Server in docker against
# test data from the ci_hsc_gen3 package.  Assumes that ci_hsc_gen3
# has been built via lsstsw in a directory adjacent to the directory
# containing this file.
services:
  butler:
    build: .
    ports:
      - "8080:8080"
    environment:
      DAF_BUTLER_REPOSITORY_INDEX: "/butler_config/repository_index.yaml"
    volumes:
      - ../ci_hsc_gen3/DATA:/butler_root
      - ./docker/compose_files:/butler_config
