# This file gives the mapping between DatasetType and the
# `lsst.daf.butler.Formatter` that handles it.
writeRecipes: !include writeRecipes.yaml
default:
  lsst.obs.base.fitsExposureFormatter.FitsExposureFormatter:
    # default is the default recipe regardless but this demonstrates
    # how to specify a default write parameter
    recipe: default
TablePersistable: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
Wcs: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
Psf: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
CoaddInputs: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
VisitInfo: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
ApCorr: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
PhotoCalib: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
TransmissionCurve: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
Camera: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
Detector: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
Catalog: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
PeakCatalog: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
SimpleCatalog: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
SourceCatalog: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
ObjectMaskCatalog: lsst.pipe.tasks.objectMasks.RegionFileFormatter
DataFrame: lsst.daf.butler.formatters.parquetFormatter.ParquetFormatter
Defects: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
QECurve: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
ImageF: lsst.obs.base.fitsExposureFormatter.FitsExposureFormatter
ImageU: lsst.obs.base.fitsExposureFormatter.FitsExposureFormatter
DecoratedImageU: lsst.obs.base.fitsExposureFormatter.FitsExposureFormatter
MaskX: lsst.obs.base.fitsExposureFormatter.FitsExposureFormatter
MaskedImageF: lsst.obs.base.fitsExposureFormatter.FitsExposureFormatter
Exposure: lsst.obs.base.fitsExposureFormatter.FitsExposureFormatter
ExposureF: lsst.obs.base.fitsExposureFormatter.FitsExposureFormatter
ExposureI: lsst.obs.base.fitsExposureFormatter.FitsExposureFormatter
SkyMap: lsst.daf.butler.formatters.pickleFormatter.PickleFormatter
Background: lsst.obs.base.fitsGenericFormatter.FitsGenericFormatter
Config: lsst.daf.butler.formatters.pexConfigFormatter.PexConfigFormatter
Packages: lsst.daf.butler.formatters.pickleFormatter.PickleFormatter
PropertyList: lsst.daf.butler.formatters.yamlFormatter.YamlFormatter
PropertySet: lsst.daf.butler.formatters.yamlFormatter.YamlFormatter
NumpyArray: lsst.daf.butler.formatters.pickleFormatter.PickleFormatter
Plot: lsst.daf.butler.formatters.matplotlibFormatter.MatplotlibFormatter
MetricValue: lsst.daf.butler.formatters.yamlFormatter.YamlFormatter
BrighterFatterKernel: lsst.daf.butler.formatters.pickleFormatter.PickleFormatter
