# Default with a sqlLite registry
registry:
  db: 'sqlite:///:memory:'
  engines:
    sqlite: lsst.daf.butler.registry.databases.sqlite.SqliteDatabase
    postgresql: lsst.daf.butler.registry.databases.postgresql.PostgresqlDatabase
    oracle: lsst.daf.butler.registry.databases.oracle.OracleDatabase
  managers:
    opaque: lsst.daf.butler.registry.opaque.ByNameOpaqueTableStorageManager
    dimensions: lsst.daf.butler.registry.dimensions.static.StaticDimensionRecordStorageManager
    collections: lsst.daf.butler.registry.collections.nameKey.AggressiveNameKeyCollectionManager
    datasets: lsst.daf.butler.registry.datasets.byDimensions.ByDimensionsDatasetRecordStorageManager
