name: build_and_test

on:
  - push
  - pull_request

jobs:
  build_and_test:
    # runs-on: ubuntu-latest
    # Need >= 20.04 for modern sqlite. Can switch to latest when
    # github change
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install sqlite
        run: sudo apt-get install sqlite libyaml-dev

      # It seems like pip install of requirements for a URL package
      # does not install those dependencies
      - name: Install sphgeom dependencies
        run: pip install -r https://raw.githubusercontent.com/lsst/sphgeom/tickets/DM-25867/requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and install
        run: pip install -v .

      - name: Run tests
        run: pytest -r a -v
