name: build_and_test

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          # Need to clone everything for the git tags.
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: Update pip/wheel infrastructure
        shell: bash -l {0}
        run: |
          conda install -y -q "pip<22" wheel

      - name: Install sqlite
        shell: bash -l {0}
        run: |
          conda install -y -q sqlite

      # Postgres-14 is already installed from official postgres repo, but we
      # also need pgsphere which is not installed. The repo is not in the list,
      # so we need to re-add it first.
      - name: Install postgresql (server)
        run: |
          sudo sh -c \
            'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install postgresql-14 postgresql-14-pgsphere

      - name: Install postgresql Python packages
        shell: bash -l {0}
        run: |
          conda install -y -q psycopg2
          pip install testing.postgresql

      - name: Install cryptography package for moto
        shell: bash -l {0}
        run: |
          conda install -y -q cryptography

      - name: Install WebDAV packages for testing
        shell: bash -l {0}
        run: |
          pip install cheroot wsgidav

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt

      # We have two cores so we can speed up the testing with xdist
      - name: Install pytest packages
        shell: bash -l {0}
        run: |
          conda install -y -q \
            "flake8<5" \
            pytest pytest-flake8 pytest-xdist pytest-openfiles pytest-cov

      - name: List installed packages
        shell: bash -l {0}
        run: |
          conda list
          pip list -v

      - name: Build and install
        shell: bash -l {0}
        run: |
          pip install -v --no-deps -e .

      - name: Run tests
        shell: bash -l {0}
        env:
          SQLALCHEMY_WARN_20: 1
        run: |
          pytest -r a -v -n 3 --open-files --cov=lsst.daf.butler --cov=tests --cov-report=xml --cov-report=term --cov-branch
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml

  pypi:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v3
        with:
          # Need to clone everything to embed the version.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade "pip<22"
          pip install --upgrade setuptools wheel build

      - name: Build and create distribution
        run: |
          python -m build --skip-dependency-check

      - name: Upload
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_UPLOADS }}
