name: docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_sphinx_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install sqlite
        run: sudo apt-get install sqlite libyaml-dev

      - name: Update pip/wheel infrastructure
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Install postgresql (server)
        run: sudo apt install postgresql

      - name: Install postgresql Python packages
        run: pip install psycopg2 testing.postgresql

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build and install
        run: pip install -v .

      - name: Install documenteer
        run: pip install 'documenteer[pipelines]<0.7'

      - name: Build documentation
        working-directory: ./doc
        run: package-docs build
