name: Run mypy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install
        run: pip install mypy pydantic

      - name: Fake a version
        run: |
          echo "__all__ = ['__version__']" > python/lsst/daf/butler/version.py
          echo "__version__ = '0.0.1'" >> python/lsst/daf/butler/version.py

      - name: Change to source directory and run mypy
        run: mypy python/lsst
